resize_size: [96, 160, 160]

data_cfg:
  dataset: "brats"
  data_root: null
  resize_size: ${resize_size}
  crop_size: [128, 192, 192]
  patch_based: False

model_cfg:
  model_type: "diffusion"
  net:
#    type: "JiT"
#    input_size: 96
#    patch_size: 8
#    in_channels: 1
#    out_channels: 1
#    use_img_cond: False
#    hidden_size: 1152 # 768 1152
#    depth: 24
#    num_heads: 16
#    mlp_ratio: 4.0
#    attn_drop: 0.
#    proj_drop: 0.
#    num_classes: 4
#    bottleneck_dim: 128
#    in_context_len: 32
#    in_context_start: 4
#    use_flash_attn: True
#    conditioned_blocks: True
#    use_y_emb: True
#    use_t_emb: False

    type: "CondUNet"
    input_channels: 1
    n_stages: 5 #6
    features_per_stage: [32, 64, 128, 256, 320]
    kernel_sizes: 3
    strides: [1, 2, 2, 2, 2]
    n_blocks_per_stage: [1, 3, 4, 6, 6] # [1, 3, 4, 6, 6]
    n_conv_per_stage_decoder: [1, 1, 1, 1] # [2, 2, 2, 2]
    num_classes: 1

    # conditioning + io consistency
    use_img_cond: False
    num_label_classes: 4
    use_t_emb: False
    use_y_emb: False

#    type: "CondTransUNet"
#    input_size: 96
#    patch_size: 16
#    in_channels: 1
#    use_img_cond: False
#    stem_dim: 32
#    n_blocks_per_stage: [1, 2, 2, 2, 13]
#
#    hidden_size: 768
##    depth: 6
#    num_heads: 12
#    mlp_ratio: 4.0
#    attn_drop: 0.0
#    proj_drop: 0.0
#    num_label_classes: 4
#    use_flash_attn: True
#    conditioned_blocks: True
#
#    use_y_emb: True
#    use_t_emb: False
#    in_context_len: 32
#    in_context_start: 0


#    type: "MetaMLP"
#    in_channels: 1
#    n_channels: 32
#    n_classes: 1
#    use_img_cond: True
#    mixer_name: "dwconv"
#    exp_r: 4
#    block_counts: [3, 4, 6, 6, 6]
#    use_skip_connection: False
#    drop_path_rate: 0.0
#    conditioned_block: True
#    use_t_emb: True,
#    use_y_emb: True

  diffusion:
    use_img_cond: False

    flow_mode: "PiF"
    drift_scale: 1
    prediction_space: "x"
    loss_space: "x"

    t_weighted: False
    t_scale: 1

    use_t_consistency: False
    lambda_t: 0.2
    mixed_batch: False

    img_size: ${resize_size}
    class_num: 4

    if_regression: True
    t_sample: "uniform"
    beta_warmup_epochs: 0
    beta1: 1
    beta2_min: 1
    beta2_max: 1
    zero_t_prob: 0
    one_t_prob: 0
    P_mean: -0.8
    P_std: 0.8
    t_eps: 0.05

    condition_drop_prob: 0.
    label_drop_prob: 0. # 0.1
    noise_scale: 1

    # ema
    use_ema: False
    ema_decay: 0.9999

    # generation hyper params
    sampling_method: "heun"
    num_sampling_steps: 1
    use_cfg: False
    cfg_scale: 0.2
    interval_min: 0.
    interval_max: 1.0

train_cfg:
  devices: 1
  num_workers: 4
  precision: "32-true"    # 16-mixed 32-true
  batch_size: 4
  num_epochs: 500
  save_freq: 50
  limit_train_batches: .inf
  loss: ["mse"]
  loss_weights:
    perceptual_vgg: 0.2

val_cfg:
  start_val: 0
  val_freq: 50
  limit_val_batches: .inf

optim_cfg:
  optimizer: "adam"
  base_lr: 2e-4
  start_factor: 0.01
  lr_min: 0.
  weight_decay: 0.0
  layer_decay: null
  warmup_epochs: 5
  grad_clip: null
  betas: [0.9, 0.95]
  eps: 1e-8
  scheduler: 'warmup'  # 'cosine', 'plateau'

automatic_lr_rescale: True



